const ERROR_SERVER_CODE = 500;
const NOT_FOUND_CODE = 404;
const UNAUTHORIZED_CODE = 401;
const ERROR_DATA_CODE = 400;
const ERROR_CONFLICT_CODE = 409;

module.exports = {
  ERROR_SERVER_CODE,
  NOT_FOUND_CODE,
  UNAUTHORIZED_CODE,
  ERROR_DATA_CODE,
  ERROR_CONFLICT_CODE,
};
